"""init auth rbac resources

Revision ID: 47f8f17ab7d5
Revises: 
Create Date: 2026-01-29 15:53:34.470392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f8f17ab7d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Permission ID'),
    sa.Column('code', sa.String(length=128), nullable=False, comment='Permission code like doc.read'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Permission description'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='Permission registry (code is stable identifier)'
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Role ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='Role name (unique)'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Role description'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='RBAC roles'
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='User ID (internal PK)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Login email (unique)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Password hash (argon2id)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Active user'),
    sa.Column('is_superadmin', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Bypass all authz'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Created time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Updated time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    comment='System users'
    )
    op.create_table('workspaces',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Workspace ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Workspace name (unique)'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Workspace description'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Created time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Updated time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_workspace_name'),
    comment='Workspace/Org container'
    )
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Project ID'),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False, comment='FK -> workspaces.id'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Project name (unique within workspace)'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Project description'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Created time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Updated time'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_ws_project_name'),
    comment='Project container under workspace'
    )
    op.create_index('idx_project_ws', 'projects', ['workspace_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='FK -> roles.id'),
    sa.Column('perm_id', sa.BigInteger(), nullable=False, comment='FK -> permissions.id'),
    sa.ForeignKeyConstraint(['perm_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'perm_id'),
    comment='Role -> Permission mapping'
    )
    op.create_table('user_identities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Identity row ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='FK -> users.id'),
    sa.Column('provider', sa.String(length=32), nullable=False, comment='Provider: local/google/okta/... (future)'),
    sa.Column('subject', sa.String(length=255), nullable=False, comment='Provider subject (OIDC sub / SAML NameID)'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Provider email (optional)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Created time'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_provider_subject'),
    comment='External identities (future SSO/OIDC/SAML)'
    )
    op.create_index('idx_user_provider', 'user_identities', ['user_id', 'provider'], unique=False)
    op.create_table('user_role_grants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Grant row ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='FK -> users.id'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='FK -> roles.id'),
    sa.Column('scope_key', sa.String(length=128), nullable=False, comment='global | workspace:{id} | project:{id} | resource:{type}:{ref_id}'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='Granting admin user_id'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Grant time'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'scope_key', name='uq_user_role_scope'),
    comment='User role grants scoped by scope_key'
    )
    op.create_index('idx_scope', 'user_role_grants', ['scope_key'], unique=False)
    op.create_index('idx_user_scope', 'user_role_grants', ['user_id', 'scope_key'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Resource row ID (internal)'),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False, comment='Owning workspace id'),
    sa.Column('project_id', sa.BigInteger(), nullable=True, comment='Owning project id (nullable)'),
    sa.Column('resource_type', sa.String(length=32), nullable=False, comment='doc/audio/image/ticket/... (extensible)'),
    sa.Column('ref_id', sa.BigInteger(), nullable=False, comment='Business table PK this resource refers to'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='Creator user_id'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Created time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Updated time'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Unified resource directory for authorization'
    )
    op.create_index('idx_type_ref', 'resources', ['resource_type', 'ref_id'], unique=False)
    op.create_index('uq_resource_ws_proj_type_ref', 'resources', ['workspace_id', 'project_id', 'resource_type', 'ref_id'], unique=True, postgresql_where=sa.text('project_id IS NOT NULL'))
    op.create_index('uq_resource_ws_type_ref_no_proj', 'resources', ['workspace_id', 'resource_type', 'ref_id'], unique=True, postgresql_where=sa.text('project_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_resource_ws_type_ref_no_proj', table_name='resources', postgresql_where=sa.text('project_id IS NULL'))
    op.drop_index('uq_resource_ws_proj_type_ref', table_name='resources', postgresql_where=sa.text('project_id IS NOT NULL'))
    op.drop_index('idx_type_ref', table_name='resources')
    op.drop_table('resources')
    op.drop_index('idx_user_scope', table_name='user_role_grants')
    op.drop_index('idx_scope', table_name='user_role_grants')
    op.drop_table('user_role_grants')
    op.drop_index('idx_user_provider', table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_table('role_permissions')
    op.drop_index('idx_project_ws', table_name='projects')
    op.drop_table('projects')
    op.drop_table('workspaces')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
